# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aeJ1Dv5t0NyApvXjaGgTr0ajfmvGySXp
"""
import streamlit as st
import pandas as pd
import joblib

# 1. LOAD MODEL
model = joblib.load("model_rumah_tebet_rf.pkl")  # pastikan namanya sama

st.set_page_config(page_title="Prediksi Harga Rumah Tebet", layout="centered")

st.title("Prediksi Harga Rumah di Tebet")
st.write("Aplikasi ini memprediksi harga rumah di kawasan Tebet berdasarkan spesifikasi bangunan.")

# 2. INPUT USER
st.subheader("Masukkan Spesifikasi Rumah")

lb = st.number_input("Luas Bangunan (m²)", min_value=10, max_value=1000, value=150, step=10)
lt = st.number_input("Luas Tanah (m²)", min_value=10, max_value=1500, value=120, step=10)
kt = st.number_input("Jumlah Kamar Tidur", min_value=1, max_value=15, value=3, step=1)
km = st.number_input("Jumlah Kamar Mandi", min_value=1, max_value=15, value=2, step=1)
grs = st.number_input("Jumlah Garasi/Carport", min_value=0, max_value=10, value=1, step=1)

# 3. PREDIKSI KETIKA TOMBOL DIKLIK
if st.button("Prediksi Harga"):
    # Bentuk DataFrame sesuai fitur training
    data_baru = pd.DataFrame({
        "LB": [lb],
        "LT": [lt],
        "KT": [kt],
        "KM": [km],
        "GRS": [grs]
    })

    pred = model.predict(data_baru)[0]

    # Format ke rupiah
    pred_rp = f"Rp {pred:,.0f}".replace(",", ".")
    st.success(f"Perkiraan harga rumah: {pred_rp}")

    st.caption("Catatan: hasil prediksi adalah estimasi berdasarkan data historis rumah di Tebet.")